<a href="https://colab.research.google.com/github/SGRGit/gwOsc/blob/Main/SineGaussianAddFeatures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
base_dir = "drive/My Drive/Colab Notebooks/SignalProc/Iteration 3"
seta = 'Signal'
setb = 'Noise'

data_dir = os.path.join(base_dir, 'data')
seta_data_dir = os.path.join(data_dir, seta)
seta_data_fnnames = os.listdir(seta_data_dir)

setb_data_dir = os.path.join(data_dir, setb)
setb_data_fnnames = os.listdir(setb_data_dir)

In [0]:
import os
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
%matplotlib inline
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img

In [71]:
from scipy.fftpack import fft
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
fs = 100

alpha = np.linspace(1, 5, num = 300)
neu = np.linspace(5, 20, num = 300)

t = np.linspace(-3, 3, 2 * 100, endpoint=False)
signal_amp = np.array(100*t)
amp = np.zeros(shape = (0, 1))
freq = np.zeros(shape = (0 , 1))

#import cv2
#q1 = np.empty((1, 150, 150, 3))
#q2 = np.empty((1, 150, 150, 3))
for a in range(0, 4):
  #img_path_a = os.path.join(seta_data_dir, seta_data_fnnames[a])
  #img_a = cv2.imread(os.path.join(seta_data_dir, seta_data_fnnames[a]))
  #img_a = cv2.resize(img_a, (150, 150))
  #q1 = np.vstack((q1, img_to_array(img_a).reshape(1, 150, 150, 3)))
  #t1 = np.ones([len(seta_data_fnnames),1]) 
  #i, q, e = signal_amp*signal.gausspulse(t, fc=1*alpha[a], retquad=True, retenv=True)
  #n = (1/neu[a])*np.array(60)*np.random.randn(len(t)) 
  #xn = i + n # Noise+Signal 
  #amp.reshape(1, 3, 200)
  amp = np.vstack((amp, (1/neu[a])*np.array(60)))
  #freq.reshape(1, 1, 1)
  #freq = np.append(freq, alpha[a])
  freq = np.vstack((freq, alpha[a]))
print(amp)
print(freq)

features = np.concatenate((amp, freq), axis= 1)
print(features)
#for b in range(0, len(setb_data_fnnames)-1, 1):
#  img_path_b = os.path.join(setb_data_dir, setb_data_fnnames[b])
#  img_b = cv2.imread(os.path.join(setb_data_dir, setb_data_fnnames[b]))
#  img_b = cv2.resize(img_b, (150, 150))
#  q2 = np.vstack((q2, img_to_array(img_b).reshape(1, 150, 150, 3)))
#  t2 = np.zeros([len(setb_data_fnnames),1])

[[12.        ]
 [11.8807947 ]
 [11.76393443]
 [11.64935065]]
[[1.        ]
 [1.01337793]
 [1.02675585]
 [1.04013378]]
[[12.          1.        ]
 [11.8807947   1.01337793]
 [11.76393443  1.02675585]
 [11.64935065  1.04013378]]


array([1.        , 1.01337793, 1.02675585, 1.04013378])

In [32]:
np.zeros(shape = (4, 1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [9]:
freq

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.04013378]])