<a href="https://colab.research.google.com/github/SGRGit/gwOsc/blob/Main/SineGaussianAddFeatures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
base_dir = "drive/My Drive/Colab Notebooks/SignalProc/Iteration 3"
seta = 'Signal'
setb = 'Noise'

data_dir = os.path.join(base_dir, 'data')
seta_data_dir = os.path.join(data_dir, seta)
seta_data_fnnames = os.listdir(seta_data_dir)

setb_data_dir = os.path.join(data_dir, setb)
setb_data_fnnames = os.listdir(setb_data_dir)

In [0]:
import os
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
%matplotlib inline
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img

In [0]:
from scipy.fftpack import fft
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
fs = 100

alpha = np.linspace(1, 5, num = 300)
neu = np.linspace(5, 20, num = 300)

t = np.linspace(-3, 3, 2 * 100, endpoint=False)
signal_amp = np.array(100*t)
amp1 = np.zeros(shape = (1, 1))
freq1 = np.zeros(shape = (1 , 1))
amp2 = np.zeros(shape = (1, 1))
freq2 = np.zeros(shape = (1 , 1))


import cv2
q1 = np.empty((1, 150, 150, 3))
q2 = np.empty((1, 150, 150, 3))

for a in range(1, len(seta_data_fnnames), 1):
  img_path_a = os.path.join(seta_data_dir, seta_data_fnnames[a])
  img_a = cv2.imread(os.path.join(seta_data_dir, seta_data_fnnames[a]))
  img_a = cv2.resize(img_a, (150, 150))
  q1 = np.vstack((q1, img_to_array(img_a).reshape(1, 150, 150, 3)))
  t1 = np.ones([len(seta_data_fnnames),1])
  amp1 = np.zeros([len(seta_data_fnnames),1])
  freq1 = np.vstack((freq1, alpha[a]))


  
for b in range(1, len(setb_data_fnnames), 1):
  img_path_b = os.path.join(setb_data_dir, setb_data_fnnames[b])
  img_b = cv2.imread(os.path.join(setb_data_dir, setb_data_fnnames[b]))
  img_b = cv2.resize(img_b, (150, 150))
  q2 = np.vstack((q2, img_to_array(img_b).reshape(1, 150, 150, 3)))
  t2 = np.zeros([len(setb_data_fnnames),1])
  amp2 = np.vstack((amp2, (1/neu[b])*np.array(60)))
  freq2 = np.zeros([len(setb_data_fnnames),1])


In [0]:
test_s = np.hstack((amp1, freq1))
test_n = np.hstack((amp2, freq2))

In [0]:
id = [i for i in range(1,len(q1)+1)]

In [0]:
q_test = (q1.reshape(1, 300, 150, 150, 3))

In [0]:
test = np.array([[[1, 2, 3],[1, 3, 5]],[[11, 22, 13],[31, 23, 45]],[[18, 22, 32],[13, 31, 53]],[[161, 232, 153],[331, 223, 245]]])

In [134]:
test.reshape(1, 2, 2, 3)

array([[[[ 1,  2,  3],
         [ 1,  3,  5]],

        [[11, 22, 13],
         [31, 23, 45]]]])

In [157]:
test1

array([[[[  1,   2,   3],
         [  1,   3,   5]],

        [[ 11,  22,  13],
         [ 31,  23,  45]],

        [[ 18,  22,  32],
         [ 13,  31,  53]],

        [[161, 232, 153],
         [331, 223, 245]]]])

In [168]:
np.append(np.ones((1, 1, 1)), test1)

array([  1.,   1.,   2.,   3.,   1.,   3.,   5.,  11.,  22.,  13.,  31.,
        23.,  45.,  18.,  22.,  32.,  13.,  31.,  53., 161., 232., 153.,
       331., 223., 245.])

In [170]:
test1

array([[[[  1,   2,   3],
         [  1,   3,   5]],

        [[ 11,  22,  13],
         [ 31,  23,  45]],

        [[ 18,  22,  32],
         [ 13,  31,  53]],

        [[161, 232, 153],
         [331, 223, 245]]]])

In [0]:
test = np.array(([1, 3, 4], [3, 5,6 ]))

In [185]:
np.hstack((test, np.ones((1, 1))))

ValueError: ignored

In [186]:
np.ones((1, 1))

array([[1.]])